# Generated by Django 4.2.11 on 2024-03-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proyectosCivil',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('proyecto', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=80)),
                ('tipoProyecto', models.CharField(max_length=150)),
                ('projectManager', models.CharField(max_length=80)),
                ('prioridad', models.PositiveIntegerField()),
                ('nuevoProyecto', models.CharField(max_length=20)),
                ('propuesta', models.CharField(max_length=20)),
                ('cantidadDias', models.PositiveIntegerField()),
                ('envioPropCliente', models.CharField(max_length=20)),
                ('clienteAprobado', models.CharField(max_length=80)),
                ('proyectoExistente', models.CharField(max_length=20)),
                ('tipoServicio', models.CharField(max_length=100)),
                ('planosCadCliente', models.CharField(max_length=80)),
                ('planosDibus', models.CharField(max_length=80)),
                ('correciones', models.CharField(max_length=80)),
                ('obervaciones', models.TextField()),
                ('fechaEntrega', models.DateField()),
                ('pc', models.CharField(max_length=80)),
            ],
        ),
    ]
