# Generated by Django 4.2.11 on 2024-03-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudCivil1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoscivil',
            name='codigo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proyectoscivil',
            name='tipoProyecto',
            field=models.TextField(),
        ),
    ]
